document.writeln("<style type=\"text/css\">");
document.writeln("body { margin-bottom:60px !important; }");
document.writeln("a, button, input { -webkit-tap-highlight-color:rgba(255, 0, 0, 0); }");
document.writeln("ul, li { list-style:none; margin:0; padding:0 }");
document.writeln(".top_bar { position: fixed; z-index: 900; bottom: 0; left: 0; right: 0; margin: auto; font-family: Helvetica, Tahoma, Arial, Microsoft YaHei, sans-serif; }");
document.writeln(".top_menu { display:-webkit-box; border-top: 1px solid #b3b3b3; display: block; width: 100%; background: rgba(255, 255, 255, 0.7); height: 40px; display: -webkit-box; display: box; margin:0; padding:0; -webkit-box-orient: horizontal; background: -webkit-gradient(linear, 0 0, 0 100%, from(#e7e4e7), to(#b9b9b9)); }");
document.writeln(".top_bar .top_menu>li { -webkit-box-flex:1; background: -webkit-gradient(linear, 0 0, 0 100%, from(rgba(0, 0, 0, 0.1)), color-stop(50%, rgba(0, 0, 0, 0.2)), to(rgba(0, 0, 0, 0.2))), -webkit-gradient(linear, 0 0, 0 100%, from(rgba(255, 255, 255, 0.1)), color-stop(50%, rgba(255, 255, 255, 0.3)), to(rgba(255, 255, 255, 0.1))); -webkit-background-size:1px 100%, 1px 100%; background-size:1px 100%, 1px 100%; background-position: 1px center, 2px center; background-repeat: no-repeat; position:relative; text-align:center; }");
document.writeln(".top_bar .top_menu li a label { padding: 3px 0 0 3px; font-size: 12px; overflow: hidden; }");
document.writeln(".top_menu>li:first-child { background:none; }");
document.writeln(".top_bar .top_menu>li>a { height:40px; line-height:40px; display:block; text-align:center; color:#4f4d4f; text-shadow: 0 1px rgba(255, 255, 255, 0.3); text-decoration:none; border-top: 1px solid #f9f9f9; -webkit-box-flex:1; }");
document.writeln(".top_bar .top_menu>li>a p { overflow:hidden; margin: 0 0 0 0; font-size: 12px; display: block !important; line-height: 18px; text-align: center; }");
document.writeln(".top_bar .top_menu>li>a img { padding: 0; height: 20px; width: 20px; color: #fff; line-height: 40px; vertical-align:middle; }");
document.writeln(".top_bar li:first-child a { display: block; }");
document.writeln(".menu_font { padding: 0; position: absolute; z-index: 500; bottom: 60px; right: 10px; width: 120px; background: #e4e3e2; border: 1px solid #afaeaf; border-radius: 5px; box-shadow: 0 1px 5px rgba(0, 0, 0, 0.2); }");
document.writeln(".menu_font.hidden { display:none; }");
document.writeln(".top_menu li:last-of-type a { background: none; }");
document.writeln(".top_menu>li:last-of-type>a label { padding: 0 0 0 3px; }");
document.writeln(".menu_font li:last-of-type { background: none; }");
document.writeln(".menu_font li a { text-align: left !important; }");
document.writeln(".top_menu li:last-of-type a { background: none; }");
document.writeln(".menu_font:before, .menu_font:after { content:\"\"; display:inline-block; position:absolute; z-index:240; bottom:0; left: 85%; margin-left:-8px; margin-bottom:-16px; width:0; height:0; border:8px solid red; border-color:#afaeaf transparent transparent transparent; }");
document.writeln(".menu_font:after { z-index:501; border-color:#e4e3e2 transparent transparent transparent; margin-bottom:-15px; margin-left:-8px; }");
document.writeln(".menu_font li { background:-webkit-gradient(linear, 0 0, 100% 0, from(#e4e3e2), to(#e4e3e2), color-stop(50%, #f3f3f2)), -webkit-gradient(linear, 0 0, 100% 0, from(#e4e3e2), to(#e4e3e2), color-stop(50%, #c6c5c5)); background-size:100% 1px, 100% 2px; background-repeat:no-repeat; background-position: center bottom; }");
document.writeln(".menu_font li:first-of-type { border-top: 0; }");
document.writeln(".menu_font li:last-of-type { border-bottom: 0; }");
document.writeln(".menu_font li a { height: 40px; line-height: 40px !important; position: relative; color: #fff; display: block; width: 100%; text-indent: 10px; white-space: nowrap; text-overflow: ellipsis; overflow: hidden; text-decoration:none; color:#4f4d4f; text-shadow: 0 1px rgba(255, 255, 255, 0.3); }");
document.writeln(".menu_font li a img { width: 20px; height:20px; display: inline-block; margin-top:-2px; color: #fff; line-height: 40px; vertical-align:middle; }");
document.writeln(".menu_font>li>a label { padding:3px 0 0 3px; font-size:14px; overflow:hidden; margin: 0; }");
document.writeln("#menu_list0 { right:0; left:10px; }");
document.writeln("#menu_list0:before, #menu_list0:after { left: 15%; }");
document.writeln("#menu_list0:after { margin-bottom:-15px; margin-left:-8px; }");
document.writeln("#sharemcover { position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0, 0, 0, 0.7); display: none; z-index: 20000; }");
document.writeln("#sharemcover img { position: fixed; right: 18px; top: 5px; width: 260px; height: 180px; z-index: 20001; border:0; }");
document.writeln(".top_bar .top_menu>li>a:hover, .top_bar .top_menu>li>a:active { background-color:#CCCCCC; }");
document.writeln(".menu_font li a:hover, .menu_font li a:active { background-color:#CCCCCC; }");
document.writeln(".menu_font li:first-of-type a { border-radius:5px 5px 0 0; }");
document.writeln(".menu_font li:last-of-type a { border-radius:0 0 5px 5px; }");
document.writeln("#plug-wrap { position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0, 0, 0, 0); z-index:800; }");
document.writeln("#cate18 .device {bottom: 49px;}");
document.writeln("#cate18 #indicator {bottom: 240px;}");
document.writeln("#cate19 .device {bottom: 49px;}");
document.writeln("#cate19 #indicator {bottom: 330px;}");
document.writeln("#cate19 .pagination {bottom: 60px;}");
document.writeln("</style>");
document.writeln("<div id=\"sharemcover\" onClick=\"document.getElementById(\'sharemcover\').style.display=\'\';\" style=\" display:none\"><img src=\"http://bcs.duapp.com/baeimg/MgnnofmleM.png\"></div>");
document.writeln("<div class=\"top_bar\" style=\"-webkit-transform:translate3d(0,0,0)\">");
document.writeln("  <nav>");
document.writeln("    <ul id=\"top_menu\"  class=\"top_menu\">");document.writeln("    	<li> <a   href=\"http://weixin.calo.com/wxapi.php?ac=cate4&amp;tid=140&amp;c=&refex=mp.weixin.qq.com\"  ><img src=\"http://bcs.duapp.com/baeimg/Lkx2QdvIF7.png\"><label>微网站</label></a>");
document.writeln("        	<ul id=\"menu_list0\" class=\"menu_font\" style=\" display:none\">");document.writeln("            </ul>");
document.writeln("        </li>");
document.writeln("    	<li> <a   href=\"http://api.map.baidu.com/marker?location=25.684849,114.78361&amp;title=%E6%B1%9F%E8%A5%BF%E6%BD%98%E5%B3%B0%E5%AE%B6%E5%B1%85%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8&amp;content=江西赣州南康市东山工业区工业一路&amp;output=html\"  ><img src=\"http://bcs.duapp.com/baeimg/FV4hGIflrO.png\"><label>微导航</label></a>");
document.writeln("        	<ul id=\"menu_list1\" class=\"menu_font\" style=\" display:none\">");document.writeln("            </ul>");
document.writeln("        </li>");
document.writeln("    	<li> <a   href=\"tel:4001699668\"  ><img src=\"http://bcs.duapp.com/baeimg/q4p5nLrtjU.png\"><label>一键拨号</label></a>");
document.writeln("        	<ul id=\"menu_list2\" class=\"menu_font\" style=\" display:none\">");document.writeln("            </ul>");
document.writeln("        </li>");
document.writeln("    	<li> <a   onClick=\"javascript:displayit(3)\" ><img src=\"http://bcs.duapp.com/baeimg/zmfAzdKBfi.png\"><label>更多</label></a>");
document.writeln("        	<ul id=\"menu_list3\" class=\"menu_font\" style=\" display:none\">");document.writeln("                <li> <a href=\"http://apisimsim.duapp.com/?ac=heka1&amp;hkid=2774\"><img src=\"http://bcs.duapp.com/baeimg/ccqQYpaAsX.png\" ><label>浪漫情人节</label></a></li>");
document.writeln("                <li> <a href=\"http://comment.duapp.com/?openid=&refex=mp.weixin.qq.com&amp;wxid=a3b07df76cb66657e70cea9976f7f8d9\"><img src=\"http://bcs.duapp.com/baeimg/J7XvZPwHb9.png\" ><label>留言反馈</label></a></li>");
document.writeln("                <li> <a href=\"http://weixin.calo.com/wxapi.php?ac=photo&amp;tid=140\"><img src=\"http://bcs.duapp.com/baeimg/Ty0PLkAniz.png\" ><label>产品赏析</label></a></li>");
document.writeln("            </ul>");
document.writeln("        </li>");
document.writeln("    </ul>");
document.writeln("  </nav>");
document.writeln("</div>");
document.writeln("<div id=\"plug-wrap\" onClick=\"closeall()\" style=\"display: none;\"></div>");
document.writeln("<script>");
document.writeln("function displayit(n){");
document.writeln("	var count = document.getElementById(\"top_menu\").getElementsByTagName(\"ul\").length;	");
document.writeln("	for(i=0;i<count;i++){");
document.writeln("		if(i==n){");
document.writeln("		 if(document.getElementById(\"top_menu\").getElementsByTagName(\"ul\").item(n).style.display==\'none\'){");
document.writeln("			 document.getElementById(\"top_menu\").getElementsByTagName(\"ul\").item(n).style.display=\'\';");
document.writeln("			 document.getElementById(\"plug-wrap\").style.display=\'\';");
document.writeln("			}else{");
document.writeln("				 document.getElementById(\"top_menu\").getElementsByTagName(\"ul\").item(n).style.display=\'none\';");
document.writeln("				  document.getElementById(\"plug-wrap\").style.display=\'none\';");
document.writeln("			}");
document.writeln("		}else{");
document.writeln("			document.getElementById(\"top_menu\").getElementsByTagName(\"ul\").item(i).style.display=\'none\';");
document.writeln("		}");
document.writeln("	}");
document.writeln("}");
document.writeln("function closeall(){");
document.writeln("	var count = document.getElementById(\"top_menu\").getElementsByTagName(\"ul\").length;	");
document.writeln("	for(i=0;i<count;i++){");
document.writeln("		 document.getElementById(\"top_menu\").getElementsByTagName(\"ul\").item(i).style.display=\'none\';");
document.writeln("	}");
document.writeln("	 document.getElementById(\"plug-wrap\").style.display=\'none\';");
document.writeln("}");
document.writeln("");
document.writeln("");
document.writeln("document.addEventListener(\'WeixinJSBridgeReady\', function onBridgeReady() {");
document.writeln("WeixinJSBridge.call(\'hideToolbar\');");
document.writeln("});");
document.writeln("</script> ");